name: CI

on: [push, pull_request]

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
      - name: Checkout gitly
        uses: actions/checkout@v3
        with:
          path: gitly
      - name: Install Dependencies
        run: sudo apt install libsqlite3-dev libgit2-dev
      - name: Install Markdown
        uses: actions/checkout@v3
        with:
          repository: vlang/markdown
          path: vlib/markdown
      - name: Install PCRE
        uses: actions/checkout@v3
        with:
          repository: vlang/pcre
          path: vlib/pcre
      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Compile gitly
        run: |
          cd gitly
          v -cc gcc .

      - name: Compile gitly with -autofree
        run: |
          cd gitly
          v -cc gcc -autofree .

      - name: Compile gitly with -prod
        run: |
          cd gitly
          v -cc gcc -prod .

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.11
        with:
          source: gitly/src/static/css/gitly.scss
          destination: gitly/src/static/css/gitly.css

      - name: Run all tests
        run: |
          cd gitly
          v -cc gcc -d use_openssl test .

      - name: Run tests/first_run.v
        run: |
          cd gitly
          v -cc gcc -g run tests/first_run.v

  macos-clang:
    runs-on: macos-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
      - name: Checkout gitly
        uses: actions/checkout@v3
        with:
          path: gitly
      - name: Install Markdown
        uses: actions/checkout@v3
        with:
          repository: vlang/markdown
          path: vlib/markdown
      - name: Install PCRE
        uses: actions/checkout@v3
        with:
          repository: vlang/pcre
          path: vlib/pcre
      - name: Install libgit2
        run: brew install libgit2
      - name: Build V
        run: |
          make
          ./v symlink
      - name: Compile gitly
        run: |
          cd gitly
          v -cc clang .
      - name: Compile gitly with -autofree
        run: |
          cd gitly
          v -cc clang -autofree .
      - name: Compile gitly with -prod
        run: |
          cd gitly
          v -cc clang -prod .
      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.11
        with:
          source: gitly/src/static/css/gitly.scss
          destination: gitly/src/static/css/gitly.css
      - name: Run all tests
        run: |
          cd gitly
          v -cc clang -d use_openssl test .
      - name: Run tests/first_run.v
        run: |
          cd gitly
          v -cc clang -g run tests/first_run.v

#  windows-msvc:
#    runs-on: windows-latest
#    env:
#      VFLAGS: -cc msvc
#    steps:
#      - name: Checkout V
#        uses: actions/checkout@v3
#        with:
#          repository: vlang/v
#      - name: Checkout gitly2
#        uses: actions/checkout@v3
#        with:
#          path: gitly
#      - name: Install SQLite
#        run: |
#          .github\workflows\windows-install-sqlite.bat
#          dir thirdparty\sqlite\
#      - name: Install Markdown
#        uses: actions/checkout@v3
#        with:
#          repository: vlang/markdown
#          path: vlib/markdown
#      - name: Install PCRE
#        uses: actions/checkout@v3
#        with:
#          repository: vlang/pcre
#          path: vlib/pcre
#      - name: Build V
#        run: |
#          ./make.bat -msvc -skip-path
#      - name: Compile gitly
#        run: |
#          .\v.exe gitly\

  windows-gcc:
    runs-on: windows-latest
    env:
      VFLAGS: -cc gcc
    steps:
      - name: Checkout V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
      - name: Checkout gitly
        uses: actions/checkout@v3
        with:
          path: gitly
      - name: Install SQLite
        run: |
          .github\workflows\windows-install-sqlite.bat
          dir thirdparty\sqlite\
      - name: Install Markdown
        uses: actions/checkout@v3
        with:
          repository: vlang/markdown
          path: vlib/markdown
      - name: Install PCRE
        uses: actions/checkout@v3
        with:
          repository: vlang/pcre
          path: vlib/pcre
      - name: Build V
        run: |
          ./make.bat -gcc
      - name: Compile gitly
        run: .\v.exe -cc gcc gitly

  ubuntu-tcc:
    runs-on: ubuntu-latest
    env:
      VFLAGS: -cc tcc -d no_backtrace -d no_segfault_handler
    steps:
      - name: Checkout V
        uses: actions/checkout@v3
        with:
          repository: vlang/v
      - name: Checkout gitly
        uses: actions/checkout@v3
        with:
          path: gitly
      - name: Install Dependencies
        run: sudo apt install libsqlite3-dev libgit2-dev
      - name: Install Markdown
        uses: actions/checkout@v3
        with:
          repository: vlang/markdown
          path: vlib/markdown
      - name: Install PCRE
        uses: actions/checkout@v3
        with:
          repository: vlang/pcre
          path: vlib/pcre
      - name: Build V
        run: |
          echo $VFLAGS
          make
          sudo ./v symlink

      - name: Compile gitly with -autofree
        run: |
          cd gitly
          v -autofree .

      - name: Compile gitly
        run: |
          cd gitly
          v .

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.11
        with:
          source: src/static/css/gitly.scss
          destination: src/static/css/gitly.css

      - name: Run all tests
        run: |
          cd gitly
          v -d use_openssl test .

      - name: Run tests/first_run.v
        run: |
          cd gitly
          v -g run tests/first_run.v
